blkpg-part.bb: fix license checksum
This fixes commit 3dea83f994d7b838ad2ddfb18527c17f056ac78a.

Fixes:

	ERROR: blkpg-part-git-r0 do_populate_lic: QA Issue: blkpg-part: The LIC_FILES_CHKSUM does not match for file://LICENSE;md5=b234ee4d69f5fce4486a80fdaf4a4263
	blkpg-part: The new md5 checksum is 1803fa9c2c3ce8cb06b4861d75310742
	blkpg-part: Here is the selected license text:
	vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
	                  GNU LESSER GENERAL PUBLIC LICENSE
	                       Version 2.1, February 1999

	 Copyright (C) 1991, 1999 Free Software Foundation, Inc.
	 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
	 Everyone is permitted to copy and distribute verbatim copies
	 of this license document, but changing it is not allowed.

	[This is the first released version of the Lesser GPL.  It also counts
	 as the successor of the GNU Library Public License, version 2, hence
	...
	necessary.  Here is a sample; alter the names:

	  Yoyodyne, Inc., hereby disclaims all copyright interest in the
	  library `Frob' (a library for tweaking knobs) written by James Random
	  Hacker.

	  <signature of Ty Coon>, 1 April 1990
	  Ty Coon, President of Vice

	That's all there is to it!
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^